### ISSUE TITLE
Automatic detectioin of java version and use of correct JVM flags 

### ISSUE THREAD

**Issue by Warchant** [soramitsu/gradle-sora-plugin#11]
Preface: https://dzone.com/articles/jvm-advent-calendar-docker-and-the-jvm

Next version of this plugin will contain automatic java version detection and we need to decide which flags to use.

Current vision:
```groovy
static String getFlagsForCurrentJavaVersion(int version) {
    def flags = []
    flags << "-XshowSettings:vm"
    flags << "-XX:+PrintFlagsFinal"
    switch (version) {
        case 8:
        case 9:
            flags << "-XX:+UnlockExperimentalVMOptions"
            flags << "-XX:+UseCGroupMemoryLimitForHeap"
            flags << "-XX:+UseContainerSupport"
            flags << "-XX:MaxRAMFraction=4"
            break
        case 10:
        case 11:
            // TODO:
            // -XX:InitialRAMPercentage
            // -XX:MaxRAMPercentage
            // -XX:MinRAMPercentage
            flags << "-XX:+UseContainerSupport"
        default:
            println(format("undefined java version: ${version}"))
    }

    return flags.join(' ')
}
```

**Comment by Warchant** [comment]
Also consider newer java versions - 12, 13

**Comment by kogeler** [comment]
`static int getShortJavaVersion() {
    def version = System.getProperty('java.version').split('\\.')
    if(version[0] == '1') {
        return version[1].toInteger()
    } else {
        return version[0].toInteger()
    }
}

static String getFlagsForCurrentJavaVersion(int version) {
    def flags = []
    flags << "-XshowSettings:vm"
    flags << "-XX:+PrintFlagsFinal"
    switch (version) {
        case 8:
            flags << "-XX:+UnlockExperimentalVMOptions"
            flags << "-XX:+UseCGroupMemoryLimitForHeap"
            flags << "-XX:+UseContainerSupport"
            flags << "-XX:MaxRAMFraction=2"
            break
        case 11:
            flags << "-XX:MaxRAMPercentage=50"
            break
        case 12:
            flags << "-XX:MaxRAMPercentage=50"
        default:
            println(format("undefined java version: ${version}"))
    }

    return flags.join(' ')
}`

[](https://medium.com/adorsys/jvm-memory-settings-in-a-container-environment-64b0840e1d9e)
[](https://merikan.com/2019/04/jvm-in-a-container/)

I tested it on different containers and services and I thing that 50% of the cgroup limit will be fine, 
(MaxRAMFraction=2 = 50 % MaxRAMFraction=4 = 25% for java8).  In fact a java application can take a little more memory than the HEAP size. User might use other tools in container, for example debug tools.

UseContainerSupport option is active by default for java 10+.

**Comment by Warchant** [comment]
Some people suggest to use these settings on java 10+:
```
-XX:InitialRAMPercentage=50
-XX:MaxRAMPercentage=70
-XX:MinRAMPercentage=50
```
What do you think? @kogeler

**Comment by kogeler** [comment]
It's OK. We can try it.

**Comment by bakhtin** [comment]
@Warchant Would you assist us with the plugin update?

**Comment by Warchant** [comment]
@bakhtin yep

**Comment by Warchant** [comment]
https://github.com/soramitsu/gradle-sora-plugin/releases/tag/0.2.0
